# -*- coding: utf-8 -*-
"""assn3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cQLEZspWMVrLrEMQGU4oqInER3fa6qNO
"""

file1=open("a.txt","r")
print(file1.read())

with open("a.txt",'r+') as f1:
  f1.read()
  f1.write("Hai \n")

with open('a.txt', 'w+') as f1:
  f1.write("Hai all \n")
  f1.write("Hai all \n")
  f1.write("Hai all \n")

with open('a.txt', 'a+') as f1:
    f1.seek(0)                      
    lines = f1.readlines()           
    f1.write("\n" + str(len(lines)))
    print(f1.read())

