# -*- coding: utf-8 -*-
"""assn6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UozOuXuELwgGeHIZJhIGRnXO8iuu-Exw
"""

print("Hello %s the value of %d(%s) is %5.4f"%("all",21/7,'pi',3.141592))

print("{2} {1} {0}".format('equal','are','All'))

a=2
b=7
print(f"The area of the given rectangle is {a*b}")

from string import Template
a="Hello"
b="all"
c=Template("$d Good evening to $e")
print (c.substitute(d=a,e=b))

