# -*- coding: utf-8 -*-
"""assn2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svxn5pM7JnyEr7DIqEQqQqLvqiCCxAKe
"""

mtuple=(1,23,232.65,"Data1")
print(mtuple)
print(len(mtuple))
print(type(mtuple))

mdic={
    "Brand":"DELL",
    "Color":"Yellow",
    "Year_of_making":2022
}
print(mdic)

mdic["Color"]="Red"
print(mdic)
mdic["Code"]=123
print(mdic)
mdic["Color"]="Yellow","Red"
print(mdic)
del mdic["Code"]
print(mdic)
mdic.update({"Model":2021})
print(mdic)

list1=["Python","Webdevelopment","data science"]
dic1={
    "Course":"Python"
}
print(dic1)
dic1["Course"]=list1
print(dic1)

dic1["class"]=1,"Class2"
print(dic1)

